export default {
  edit: 'Editar',
  save: 'Salvar',
  sair: 'Sair',
  delete: 'Excluir',
  cancel: 'Cancelar',
  select: 'Selecionar',
  logout: 'Sair',
  goBack: 'Voltar',
  openMenu: 'Abrir menu',
  closeMenu: 'Fechar menu',
  takeMeBack: 'Me leve de volta',
  backToStart: 'De volta ao inicio',
  changePassword: 'Alterar senha',
  changeLanguage: 'Alterar idioma',
  searchPlaceholder: 'Pesquisar...',
  createRecord: 'Criar registro',
  editRecord: 'Editar registro',
  deleteRecord: 'Excluir registro',
  resetPassword: 'Redefinir senha',
  recoverPassword: 'Recuperar senha',
  redeemPassword: 'Redefinir senha',
  changeEstablishment: 'Trocar estabelecimento',
  closeSnackbar: 'Fechar mensagem',
};
