export default {
  internalError: 'Erro interno',
  registerNotFound: 'Registro não encontrado!',
  registerSaved: 'Registro salvo com sucesso!',
  registerDeleted: 'Registro excluído com sucesso!',
  registerUpdated: 'Registro atualizado com sucesso!',
  registerAquired: 'Registro adquirido com sucesso!',
  errorOnGetFile: 'Erro ao obter o arquivo do registro',
  errorOnUploadFile: 'Erro ao enviar o arquivo',
  noRecords: 'Sem registros',
  duplicateRecordError: 'Já existe um registro com esse valor',
  selectedIcon: 'Ícone selecionado:',
  permissions: 'Permissões: ',
  image: 'Imagem: ',
  general: 'Geral',
  establishment: 'Estabelecimento',
  resetPassword: 'Redefinir senha',
  verifyEmail: 'Verificar email',
  contact: 'Contato',
  welcome: 'Seja bem-vindo',
  errorOnDownloadFile: 'Erro ao baixar o arquivo',
  size: 'Tamanho',
  dimensions: 'Dimensões',
  profile: 'Perfil',
  login: 'Entrar',
  recoverPassword: 'Recuperar senha',
  redeemPassword: 'Criar senha',
  rowsPerPage: 'Linhas por página',
  of: 'de',
  all: 'Todos',
};
