export default {
  internalError: 'Erro interno',
  registerNotFound: 'Registro não encontrado!',
  registerSaved: 'Registro salvo com sucesso!',
  registerDeleted: 'Registro excluído com sucesso!',
  registerUpdated: 'Registro atualizado com sucesso!',
  registerAquired: 'Registro adquirido com sucesso!',
  errorOnGetFile: 'Erro ao obter o arquivo do registro',
  errorOnUploadFile: 'Erro ao enviar o arquivo',
  noRecords: 'Sem registros',
  duplicateRecordError: 'Já existe um registro com esse valor',
  selectedIcon: 'Ícone selecionado:',
  permissions: 'Permissões: ',
  image: 'Imagem: ',
  general: 'Geral',
  establishment: 'Estabelecimento',
  resetPassword: 'Redefinir senha',
  verifyEmail: 'Verificar email',
  contact: 'Contato',
  welcome: 'Seja bem-vindo',
  errorOnDownloadFile: 'Erro ao baixar o arquivo',
  size: 'Tamanho',
  dimensions: 'Dimensões',
  profile: 'Perfil',
  login: 'Entrar',
  recoverPassword: 'Recuperar senha',
  redeemPassword: 'Criar senha',
  rowsPerPage: 'Linhas por página',
  of: 'de',
  all: 'Todos',
  noRecordsFound: 'Nenhum registro encontrado',
  yesDeleteRecord: 'Sim, excluir registro',
  deleteDialogMessage:
    'Você realmente quer excluir este registro? Não será possível restaurar este item após a exclusão.',
  areYouSure: 'Você tem certeza?',
  pageNotFoundTitle: 'Página não encontrada',
  unexpectedErrorTitle: 'Erro inesperado',
  pageNotFoundMessage:
    'A página que você está procurando não existe ou foi movida.',
  unexpectedErrorMessage:
    'Ocorreu um erro inesperado. Por favor, tente novamente mais tarde.',
  passwordResetSuccess:
    'Senha redefinida com sucesso! Você pode fazer login agora.',
  copyRight: (year: string) =>
    `Copyright © ${year}. Todos os direitos reservados`,
  loggedSuccessfully: 'Logado com sucesso!',
  forgotPassword: 'Esqueceu a senha?',
  emailSentSuccess: 'Email enviado com sucesso!',
  resetPasswordButton: 'Redefinir senha',
  resetPasswordText:
    'Digite seu e-mail abaixo. Se houver uma conta associada a este endereço, enviaremos um link para redefinir sua senha.',
  createPasswordButton: 'Criar senha',
  createPasswordText: (length: string) =>
    `Digite sua nova senha abaixo. Lembre-se de usar uma senha segura com pelo menos ${length} caracteres`,
  profilePicture: 'Foto de perfil',
};
